spring:
  application:
    name: gateway-service

  messages:
    encoding: UTF-8

  r2dbc:
    url: r2dbc:postgresql://0.0.0.0:15432/
    username: mike1
    password: ENC(Dkh8b8epohII27BSx31zIg==)
    driverClassName: org.postgresql.Driver

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

server:
  port: 8085