spring:
  application:
    name: gateway-service

  messages:
    encoding: UTF-8

  r2dbc:
    url: r2dbc:postgresql://0.0.0.0:15432/
    username: ${POSTGRES_USER}
    password: ENC(Dkh8b8epohII27BSx31zIg==)
    driverClassName: org.postgresql.Driver

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: finmonitoring
          uri: http://localhost:8084
          predicates:
            - Path=/finmonitoring/v1/**
server:
  port: 8085
security:
  paths:
    public-get:
      - /login
      - /signup
      - /logout
      - /static/public/css/*
      - /GatewayApp/src/main/resources/static/public/css/*
      - /users/static/public/css/*
    public-post:
      - /users/v1/users
    authenticated-get:
      - /users/v1/users/*
      - /logout
      - /
      - /users/v1/user_authorities
      - /selfinfo
    admin-get:
      - /users/v1/users
    monitoring-get:
      - /finmonitoring/v1/*
      - /finmonitoring/v1/*/*
      - /expertises
      - /found_res
      - /save_res
      - /upd_res
      - /GatewayApp/src/main/resources/templates/*
      - /ExpertiseMonitoringService/src/main/resources/templates/*
    monitoring-post:
      - /found_res
      - /finmonitoring/v1/*
      - /finmonitoring/v1/*/*
      - /index