version: '3.1'
services:
  db_postgres_client_profiler:
    image: 'postgres:latest'
    container_name: db_postgres
    ports:
      - "15432:5432"
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  migrate:
    build:
      context: ../MigrationService/
      dockerfile: Dockerfile
    container_name: migrate
    env_file:
      - .env
    ports:
      - "15432:5432"
    depends_on:
      - db_postgres_client_profiler
    network_mode: host


  expertise_monitoring:
    build:
      context: ../ExpertiseMonitoring/
      dockerfile: Dockerfile
    container_name: expertise_monitoring
    env_file:
      - .env_sc
    ports:
      - "8084:8084"
    depends_on:
      - db_postgres_client_profiler
    network_mode: host

  gateway_app:
    build:
      context: ../GatewayApp/
      dockerfile: Dockerfile
    container_name: gateway_app
    env_file:
      - .env_sc
    ports:
      - "8085:8085"
    depends_on:
      - db_postgres_client_profiler
      - expertise_monitoring
    network_mode: host