version: '3.4'
services:
  db_postgres_client_profiler:
    image: 'postgres:latest'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d default"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    container_name: db_postgres
    ports:
      - "15432:5432"
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  migrate:
    build:
      context: ../MigrationService/
      dockerfile: Dockerfile
    container_name: migrate
    env_file:
      - .env
    ports:
      - "15432:5432"
    depends_on:
      db_postgres_client_profiler:
        condition: service_healthy
    network_mode: host


  expertise_monitoring:
    build:
      context: ../ExpertiseMonitoring/
      dockerfile: Dockerfile
    container_name: expertise_monitoring
    env_file:
      - .env_sc
    ports:
      - "8084:8084"
    depends_on:
      db_postgres_client_profiler:
        condition: service_healthy
    network_mode: host

  gateway_app:
    build:
      context: ../GatewayApp/
      dockerfile: Dockerfile
    container_name: gateway_app
    env_file:
      - .env_sc
    ports:
      - "8085:8085"
    depends_on:
      db_postgres_client_profiler:
        condition: service_healthy
      expertise_monitoring:
        condition: service_started
    network_mode: host