version: '3.1'
services:
  db_postgres_client_profiler:
    image: 'postgres:latest'
    container_name: db_postgres
    ports:
      - "15432:5432"
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - ELASTIC_PASSWORD=crn
#      - xpack.security.enabled=true
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      - elastic
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.12.0
#    container_name: kibana
#    environment:
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=crn
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch
#    networks:
#      - elastic
#volumes:
#  elasticsearch-data:
#    driver: local
#networks:
#  elastic:
#    driver: bridge