DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
login VARCHAR(30) NOT NULL,
password VARCHAR(60) NOT NULL,
granted_authority VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS EXPERTISES;
CREATE TABLE EXPERTISES (
id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
expertise_type VARCHAR(30) NOT NULL,
client_id VARCHAR(36) NOT NULL,
status VARCHAR(30) NOT NULL,
comment VARCHAR(1000) ,
dt_expertise_status timestamp without time zone NOT NULL
);